version: '3.8'

services:
  littletools:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8228:8228"
    volumes:
      - ./image:/app/image
    working_dir: /app
    command: ["./main"]
